### ISSUE TITLE
Feedback for Hashes vs Objects Blog Post

### ISSUE THREAD

**Issue by jeder28** [StevenXL/stevenxl.github.io#1]
Hey Steven,

I enjoyed reading your post on comparisons for Ruby Hashes and Javascript Objects, especially your intro that went into a little detail of the benefits and uses for each language and how you explained how to create both.

Feedback: I would love to see a more detailed example of using prototypes since I was little confused about what your example would do/ return.

Thanks,
Heather

**Comment by jeder28** [comment]
p.s. I think the link to your c7 post is broken.

**Comment by StevenXL** [comment]
Thanks for the feedback @jeder28! Fixed the issue with the linking.
